name: "Release: Scheduled"

permissions: {}

on:
  schedule:
    - cron: "0 0 * * 4" # Every Thursday at 00:00 AM UTC on the default branch
  workflow_dispatch:

jobs:
  release-schedule:
    name: "Release: Scheduled"
    uses: dargmuesli/github-actions/.github/workflows/release-schedule.yml@6989da1490699f854d6556dd2d9b862f5cbdd305 # 5.0.0-beta.1
    permissions:
      contents: read
    secrets:
      GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
    with:
      GH_APP_ID: ${{ vars.GH_APP_ID }}
      IS_DEBOUNCED: ${{ github.event_name != 'workflow_dispatch' }}
